### ISSUE TITLE
Cache when loading page during stats:fetch stores incomplete data

### ISSUE THREAD

**Issue by jakebathman** [tighten/ozzie#107]
### Recreate

1. Run `php artisan stats:fetch`
2. While this is running, refresh the index page

The beginning of `stats:fetch` calls:

```php
cache()->clear();
```

Since only `stats:fetch` updates the cached data, we could simply move the `cache()->clear()` call to the end of `stats:fetch`.

**Comment by techenby** [comment]
We just fixed this in #71
