### ISSUE TITLE
Make a project hidden if archived in GitHub

### ISSUE THREAD

**Issue by techenby** [tighten/ozzie#175]
With the GitHub integration there are a lot of projects that we aren't actively maintaining in the UI and in the Slack notifications.

PR #154 gave us the ability to hide projects, but requires a change to the data in the database.

In addition to that, I think it would be a good idea to automatically hide projects that are archived in GitHub.

**Comment by mattstauffer** [comment]
Totally agreed!

**Comment by techenby** [comment]
I'll try to get this done on Friday!

**Comment by techenby** [comment]
So we already exclude archived GitHub projects when importing 😅. I guess we just have that many older projects that we haven't archived.
