### ISSUE TITLE
Update issues with the npm fix-css command

### ISSUE THREAD

**Issue by mattstauffer** [tighten/ozzie#66]
A. it shouldn't be running on generated CSS _or_
B. we need to fix a lot of our CSS _or_
C. this isn't a good ruleset for _us_

Sadly I can't even remember where this came from.

When I ran it today I got this:

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/151829/95137347-d8fc3300-0735-11eb-914b-fd902d41576f.png">

**Comment by jonsugar** [comment]
Hmm, looks like all that .markdown-body stuff came from the PR overlay I introduced.

**Comment by sbine** [comment]
Since the overlay styles are almost like library code, how about we bundle them into a separate .css file (e.g. `vendor.css`) and just don't lint it?

**Comment by mattstauffer** [comment]
@sbine Sounds good to me!
