### ISSUE TITLE
Add an anchor tag for each repository

### ISSUE THREAD

**Issue by josecanhelp** [tighten/ozzie#78]
Create and anchor tag for each repository. This would allow links to be created that direct users to the section of the page for that repo.

An example link would be:

`https://ozzie.tighten.co/#takeout`

**Comment by JelmerIJff** [comment]
Can you assign this to me? This is my first open source contribution ever so i'm gonna do the best i can!

**Comment by josecanhelp** [comment]
We believe in you, @JelmerIJff! Looking forward to your contribution.

**Comment by JelmerIJff** [comment]
Thanks! But the anchors are already there or am i missing something? example: https://ozzie.tighten.co/#project-tighten-collect

**Comment by marcusmoore** [comment]
🤔 Yup...you're right.

I think we can improve this though...

1. Can we update the url to only use the package name like in Jose's first comment? So anchors would look like `ozzie.tighten.co/#collect`
1. Can we add an icon and anchor next to the project's name? Essentially what Laravel's docs do for each subsection. That way we can click it and grab the url from the location bar easily? I think the [link svg in Zondicons](https://www.zondicons.com/icons.html) would work out nicely.

**Comment by jakebathman** [comment]
Your first idea wouldn't necessarily work, because the [move to MySQL-stored projects](https://github.com/tighten/ozzie/pull/72) makes the project name no longer guaranteed unique.

We could render them with a number suffix if there are duplicates to get around this, but just keep that in mind.

**Comment by marcusmoore** [comment]
That thought came to mind _but_ I figured _most_ users won't have duplicate project names. But you're right...even though the page would still render the html wouldn't be valid.

@JelmerIJff, let's go with `#tighten-collect`.

**Comment by JelmerIJff** [comment]
#79
