### ISSUE TITLE
The "synced" time on the page doesn't respect stats:fetch time

### ISSUE THREAD

**Issue by mattstauffer** [tighten/ozzie#87]
![image](https://user-images.githubusercontent.com/151829/104939007-dd172e00-597d-11eb-9a56-bd4501da2464.png)

What was the original intention for this time @jakebathman? Or is it supposed to update when stats:fetch runs and just failing to do so? Thanks!

**Comment by mattstauffer** [comment]
OK, it's now respect pulls on `stats:fetch`, but if the stats that come back are exactly the same as before, it won't show as "updated", so I think we could update `FetchProjectStats` to touch the `updated_at` even if no changes were made.

**Comment by jakebathman** [comment]
IIRC the idea was to only updated the timestamp here if the data changed. Otherwise, each project doesn't need a timestamp and we could put the `stats:fetch` time somewhere else near the top of the page.

**Comment by mattstauffer** [comment]
Oh. Right. Duh. Ok. :) thanks!
