### ISSUE TITLE
Enhancement request: Docker config for local development

### ISSUE THREAD

**Issue by SecondeJK** [tighten/ozzie#91]
This is a debatable request because it's some maintainers preferences not to have ops configs littered all around source code repositories.

Proposing to add a docker directory with a docker-compose and docker files for PHP and mysql so that local ozzie development can be one-command install to get up and running. If approved by maintainers I can open a PR for it.

**Comment by mattstauffer** [comment]
👍🏻 Thanks for asking, sounds great!

**Comment by SecondeJK** [comment]
Would be closed by #92
